"""
Email composition and delivery via SMTP (Gmail / Outlook / any TLS SMTP).
"""

from __future__ import annotations

import smtplib
import ssl
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any


# ---------------------------------------------------------------------------
# HTML email template (inline styles for broad client compatibility)
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AWS Service Updates</title>
</head>
<body style="margin:0;padding:0;background:#f4f4f4;font-family:Arial,Helvetica,sans-serif;">

<!-- Header -->
<table width="100%" cellpadding="0" cellspacing="0" border="0">
  <tr>
    <td align="center" style="background:#232f3e;padding:24px 0;">
      <table width="600" cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td style="color:#ff9900;font-size:26px;font-weight:bold;letter-spacing:1px;">
            &#9729; AWS Service Updates
          </td>
          <td align="right" style="color:#aab3bf;font-size:13px;vertical-align:bottom;">
            {date_str}<br>Last {days_back} day{days_plural}
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

<!-- Body -->
<table width="100%" cellpadding="0" cellspacing="0" border="0">
  <tr>
    <td align="center" style="padding:24px 0;">
      <table width="600" cellpadding="0" cellspacing="0" border="0">

        {service_blocks}

        <!-- Footer -->
        <tr>
          <td style="padding-top:32px;border-top:1px solid #ddd;color:#999;font-size:11px;text-align:center;">
            Generated by AWS RSS Digest &nbsp;|&nbsp;
            <a href="https://aws.amazon.com/about-aws/whats-new/" style="color:#999;">AWS What's New</a>
            &nbsp;|&nbsp;
            <a href="https://aws.amazon.com/blogs/aws/" style="color:#999;">AWS Blog</a>
          </td>
        </tr>

      </table>
    </td>
  </tr>
</table>

</body>
</html>
"""

_SERVICE_BLOCK = """\
<tr>
  <td style="padding-bottom:24px;">
    <!-- Service header -->
    <table width="100%" cellpadding="0" cellspacing="0" border="0">
      <tr>
        <td style="background:#ff9900;padding:8px 14px;border-radius:4px 4px 0 0;">
          <span style="color:#fff;font-size:15px;font-weight:bold;">{service_name}</span>
          <span style="color:#fff4e0;font-size:12px;margin-left:8px;">({item_count} update{plural})</span>
        </td>
      </tr>
    </table>
    <!-- Items -->
    <table width="100%" cellpadding="0" cellspacing="0" border="0"
           style="background:#fff;border:1px solid #ddd;border-top:none;border-radius:0 0 4px 4px;">
      {item_rows}
    </table>
  </td>
</tr>
"""

_ITEM_ROW = """\
<tr>
  <td style="padding:14px 16px;border-bottom:1px solid #f0f0f0;">
    <a href="{link}" style="color:#1a73c8;font-size:14px;font-weight:bold;text-decoration:none;">{title}</a>
    <div style="color:#777;font-size:11px;margin:3px 0 6px;">{date_str}</div>
    <div style="color:#444;font-size:13px;line-height:1.5;">{summary}</div>
    <div style="margin-top:8px;">
      <a href="{link}" style="color:#ff9900;font-size:12px;text-decoration:none;">Read more &rarr;</a>
    </div>
  </td>
</tr>
"""

_NO_ITEMS_ROW = """\
<tr>
  <td style="padding:14px 16px;color:#999;font-size:13px;font-style:italic;">
    No updates found for this service in the selected time window.
  </td>
</tr>
"""


# ---------------------------------------------------------------------------
# Plain-text fallback
# ---------------------------------------------------------------------------

def _build_plain_text(results: dict[str, list[dict]], days_back: int) -> str:
    now = datetime.now(timezone.utc)
    lines = [
        "AWS SERVICE UPDATES",
        f"Generated: {now.strftime('%Y-%m-%d %H:%M UTC')}",
        f"Covering last {days_back} day{'s' if days_back != 1 else ''}",
        "=" * 60,
        "",
    ]
    for service_name, items in results.items():
        lines.append(f"## {service_name} ({len(items)} update{'s' if len(items) != 1 else ''})")
        if not items:
            lines.append("  No updates found.")
        for item in items:
            date_str = item["published"].strftime("%Y-%m-%d") if item["published"] else "Unknown"
            lines.append(f"  [{date_str}] {item['title']}")
            if item["summary"]:
                lines.append(f"  {item['summary'][:200]}")
            lines.append(f"  {item['link']}")
            lines.append("")
        lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML builder
# ---------------------------------------------------------------------------

def build_html_email(results: dict[str, list[dict]], days_back: int) -> str:
    """Render the full HTML email from scraped results."""
    now = datetime.now(timezone.utc)
    date_str = now.strftime("%B %d, %Y")

    service_blocks_html = ""
    for service_name, items in results.items():
        item_rows_html = ""
        if not items:
            item_rows_html = _NO_ITEMS_ROW
        else:
            for item in items:
                d = item["published"].strftime("%B %d, %Y %H:%M UTC") if item["published"] else "Unknown date"
                item_rows_html += _ITEM_ROW.format(
                    link=item["link"] or "#",
                    title=_esc(item["title"]),
                    date_str=d,
                    summary=_esc(item["summary"]),
                )

        service_blocks_html += _SERVICE_BLOCK.format(
            service_name=_esc(service_name),
            item_count=len(items),
            plural="s" if len(items) != 1 else "",
            item_rows=item_rows_html,
        )

    return _HTML_TEMPLATE.format(
        date_str=date_str,
        days_back=days_back,
        days_plural="s" if days_back != 1 else "",
        service_blocks=service_blocks_html,
    )


def _esc(text: str) -> str:
    """Minimal HTML escaping for inline content."""
    return (
        text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
    )


# ---------------------------------------------------------------------------
# SMTP send
# ---------------------------------------------------------------------------

def send_email(
    html_body: str,
    recipients: list[str],
    subject: str,
    smtp_config: dict,
) -> None:
    """
    Send an HTML email via SMTP.

    Raises an exception on failure so the caller can surface the error.
    """
    if not recipients:
        raise ValueError("No recipients specified.")

    plain_body = "Please view this email in an HTML-capable client."

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = smtp_config["username"]
    msg["To"] = ", ".join(recipients)

    msg.attach(MIMEText(plain_body, "plain", "utf-8"))
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    host = smtp_config["host"]
    port = int(smtp_config.get("port", 587))
    username = smtp_config["username"]
    password = smtp_config["password"]
    use_tls = smtp_config.get("tls", True)

    context = ssl.create_default_context()

    if use_tls:
        with smtplib.SMTP(host, port, timeout=30) as server:
            server.ehlo()
            server.starttls(context=context)
            server.ehlo()
            server.login(username, password)
            server.sendmail(username, recipients, msg.as_string())
    else:
        with smtplib.SMTP_SSL(host, port, context=context, timeout=30) as server:
            server.login(username, password)
            server.sendmail(username, recipients, msg.as_string())


def test_smtp_connection(smtp_config: dict) -> tuple[bool, str]:
    """
    Test SMTP credentials without sending a message.
    Returns (success: bool, message: str).
    """
    try:
        host = smtp_config["host"]
        port = int(smtp_config.get("port", 587))
        username = smtp_config["username"]
        password = smtp_config["password"]
        use_tls = smtp_config.get("tls", True)

        if not host or not username or not password:
            return False, "Host, username, and password are required."

        context = ssl.create_default_context()
        if use_tls:
            with smtplib.SMTP(host, port, timeout=15) as server:
                server.ehlo()
                server.starttls(context=context)
                server.ehlo()
                server.login(username, password)
        else:
            with smtplib.SMTP_SSL(host, port, context=context, timeout=15) as server:
                server.login(username, password)

        return True, f"Connected to {host}:{port} successfully."
    except smtplib.SMTPAuthenticationError:
        return False, "Authentication failed. Check your username and password."
    except smtplib.SMTPConnectError as e:
        return False, f"Could not connect to {smtp_config.get('host', '')}:{smtp_config.get('port', 587)} — {e}"
    except Exception as e:
        return False, str(e)


def build_subject(template: str) -> str:
    """Substitute {date} in the subject template."""
    return template.replace("{date}", datetime.now().strftime("%Y-%m-%d"))
